name: DevOps

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.4.2
      - run: npx prettier --check *.{json,yml}

